version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: mediconnect_prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mediconnect_net

networks:
  mediconnect_net:
    driver: bridge
