version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mediconnect_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mediconnect
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mediconnect_net

networks:
  mediconnect_net:
    driver: bridge

volumes:
  postgres_data:
